window.STOCK_LIBRARY = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "MSFT", name: "Microsoft", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "NVDA", name: "NVIDIA", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "ASML", name: "ASML Holding", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "GOOGL", name: "Alphabet", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "META", name: "Meta Platforms", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer", exchange: "NASDAQ" },
  { symbol: "TSLA", name: "Tesla", sector: "Consumer", exchange: "NASDAQ" },
  { symbol: "WMT", name: "Walmart", sector: "Consumer", exchange: "NYSE" },
  { symbol: "KO", name: "Coca-Cola", sector: "Consumer", exchange: "NYSE" },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer", exchange: "NYSE" },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials", exchange: "NYSE" },
  { symbol: "V", name: "Visa", sector: "Financials", exchange: "NYSE" },
  { symbol: "MA", name: "Mastercard", sector: "Financials", exchange: "NYSE" },
  { symbol: "BAC", name: "Bank of America", sector: "Financials", exchange: "NYSE" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", exchange: "NYSE" },
  { symbol: "LLY", name: "Eli Lilly", sector: "Healthcare", exchange: "NYSE" },
  { symbol: "UNH", name: "UnitedHealth", sector: "Healthcare", exchange: "NYSE" },
  { symbol: "XOM", name: "Exxon Mobil", sector: "Energy", exchange: "NYSE", cik: "0000034088" },
  { symbol: "CVX", name: "Chevron", sector: "Energy", exchange: "NYSE" },
  { symbol: "NEE", name: "NextEra Energy", sector: "Energy", exchange: "NYSE" },
  { symbol: "DIS", name: "Walt Disney", sector: "Media", exchange: "NYSE" },
  { symbol: "NFLX", name: "Netflix", sector: "Media", exchange: "NASDAQ" },
  { symbol: "CMCSA", name: "Comcast", sector: "Media", exchange: "NASDAQ" },
  { symbol: "COST", name: "Costco", sector: "Consumer", exchange: "NASDAQ" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc", sector: "Technology", exchange: "NASDAQ", cik: "0000002488" }
];
